baseURL = 'https://pooria.online/'
locale = 'en-us'
title = "pourya:/var/log"
theme = 'pourya'

[taxonomies]
tag = 'tags'

[params]
description = "Homepage"
theme = 'auto'
homeIntroTitle = "About Me"
homeIntroContent = """
I'm [Pourya](https://en.wikipedia.org/wiki/Pouria) Mokhtari, a computer engineer specializing in distrubted systems, applied machine learning and cryptography. I'm currently a research assistant at [Information, Network and Learning Labs](https://inl-lab.net) in Sharif University of Technology.

My research focuses on developing machine-learning models for detecting anomalies in the context of Intrusion Detection Systems.
"""
homeCollectionTitle = 'Posts'
homeCollection = 'posts'
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'
breadcrumbs = false
footerCopyright = "All content on this web page is written by a human."
avatar = "/images/avatar.jpg"

[[params.social]]
name = "email"
url = "mailto:contact@pouryamokhtari.com"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/pooriamokhtari/"

[[params.social]]
name = "github"
url = "https://github.com/p0m0h3"

[[menus.main]]
name = "posts"
url = "/posts"
weight = 1

[[menus.main]]
name = "about"
url = "/about"
weight = 2

summaryLength = 30

[markup.highlight]
noClasses = false
